name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:

  # 2024-12-24 : kcov v42 wants libopcodes-2.38-system and this is no longer
  # what is in place on the runners

  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4

      # This is v1.0.0, Apr 14, 2022
      - uses: tlylt/install-graphviz@b2201200d85f06f0189cb74d9b69208504cf12cd

      # This is v2.0.1, May 24, 2025
      - uses: mlugg/setup-zig@7dccf5e6d09267c55f815f2db29495f30ba2ebca

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: make structure graph
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: visualization
          path: |
            zig-out/visual.svg
            zig-out/visual.dot
            zig-out/visual.yml            

# EOF
