name: Build and Test

on:
  workflow_dispatch:
  pull_request:

jobs:

  # 2024-12-24 : kcov v42 wants libopcodes-2.38-system and this is no longer
  # what is in place on the runners

  lint:
    runs-on: ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
      - uses: nektro/actions-setup-zigmod@v1
      - run: zigmod aq install 1/nektro/ziglint
      - run: ~/.zigmod/bin/ziglint -skip todo

  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4

      - uses: tlylt/install-graphviz@v1

      - uses: mlugg/setup-zig@v1

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: make structure graph
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: visualization
          path: |
            zig-out/visual.svg
            zig-out/visual.dot
            zig-out/visual.yml            

# EOF
