name: Build and Test

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:

jobs:

  # 2024-12-24 : kcov v42 wants libopcodes-2.38-system and this is no longer
  # what is in place on the runners

  build-and-test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v4

      - uses: tlylt/install-graphviz@v1

      - uses: mlugg/setup-zig@v1

      - name: Build
        run: zig build

      # Also generates test binary which we run in coverage

      - name: Test
        run: zig build test

      - name: Make visualize.svg
        run: make

      # NOTE: does not actually work.
      #
      #    https://github.com/SimonKagstrom/kcov/issues/151
      #
      # You need to set the security to unconfined in order to utilize the
      # personality() system call
      #
      #    docker run -it --rm --security-opt seccomp=unconfined -v $(pwd):/source kcov
      #
      - name: Generate coverage
        uses: sudo-bot/action-kcov@latest
        with:
          cli-args: '--exclude-pattern opt ${{ runner.temp }}/coverage ./zig-out/bin/test'

      - uses: actions/upload-artifact@v4
        with:
          name: zrogue
          path: |
            visualize.svg
            ${{ runner.temp }}/coverage

# EOF
